version: '3.5'
services:
  mongo:
    image: mongo:6.0.6
    container_name: db_mongo
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    env_file:
      - .env
  backend:
    image: backend
    build: .
    depends_on:
      - mongo
    container_name: backend
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    name: backend
volumes:
  mongodata:
