version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo
    container_name: mongodb
    expose:
      - '27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - bridge-network

  # Node.js application service
  node-app:
    build: .
    container_name: node-app
    depends_on:
      - mongo
    env_file:
      - .env
      - .env.production
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  mongo_data:
