version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Node.js application service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile for the Node.js app
    container_name: node-app
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    env_file:
      - .env # Load environment variables from the .env file
    environment:
      - DB_URL=mongodb://mongo:27017/leet-coders-bot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
